### PR TITLE
fix(config-set): Don't attempt to merge array-valued config items.

### LINKED ISSUE #168: Oddity with PR 151; handling of JSON array merging
Start with local memcache with no data (command `flush_all`). Then do this
```
File ary.json:

{
  "allowedIPs": [ 
    "55.55.55.55"
  ]
}

$ ./scripts/config-list.js 127.0.0.1:11211; \
    cat /tmp/ary.json | ./scripts/config-set.js 127.0.0.1:11211; \
    echo @@@@@; ./scripts/config-list.js 127.0.0.1:11211
no limits set
no allowedIPs set
no allowedEmailDomains set
no requestChecks set
{
  "limits": {},
  "allowedIPs": [],
  "allowedEmailDomains": [],
  "requestChecks": {}
}
@@@@@
no limits set
no allowedEmailDomains set
no requestChecks set
{
  "limits": {},
  "allowedIPs": {
    "0": "55.55.55.55"
  },
  "allowedEmailDomains": [],
  "requestChecks": {}
}
```

So `allowedIPs` comes back as a hash with numeric keys. This was not the previous behaviour. (And yeah, an Array is an Object with numeric keys and a .length, but....).

### PR DESCRIPTION
**Pull request by rfk**
Fixes #168; @jrgm r?

### CODE REVIEW

File: scripts/config-set.js [hunk 1]
```diff
@@ -47,6 +48,20 @@ function writeMergedSettings(mc, key, newSettings) {
     )
 }
 
+function clobberSettings(mc, key, newSettings) {
```
Comment (jrgm) [inline scripts/config-set.js]: Could throw in:
```
+  if (! Array.isArray(newSettings)) {
+    console.error('newSettings is not an Array', newSettings)
+  }
```
FWIW. Type checking "hashes" is left as an exercise to the reader.
