### PR TITLE
fix(sms): Add ability to rate-limit sms by email

### LINKED ISSUE #188: SMS throttled limit is not honored for a specific FxA account if different machines are used for sending SMSs
Prerequisite:
1. Existing SessionToken
2. Availability of multiple machines

STR:
1. On a specific machine, navigate to 'https://accounts.firefox.com/sms?service=sync'
2. Enter phone number in mobile number field and click send to send SMS.
3. Repeat step 1 and 2 for 4 times to send 4 messages to valid phone numbers within quick span (less than an hour).
4. Using the same FxA account repeat step 1, 2, & 3 on multiple machines (same office wifi/IP Address) .

Expected: SMS throttled limit of 5 messages should be honored for a specific FxA account even if different machines (same office wifi/IP Address) are used for sending SMSs.

Actual: SMS throttled limit is not honored for a specific FxA account if different machines (same office wifi/IP Address) are used for sending SMSs.

For e.g. It is very much possible to send up to 40 SMSs from the same FxA account if the user tries from 10 different systems.

### PR DESCRIPTION
**Pull request by vbudhram**
This PR adds ability to rate limit SMS actions by email.

Fixes #188 

@rfk @seanmonstar r?

### CODE REVIEW

File: lib/email_record.js [hunk 1]
```diff
@@ -82,6 +84,30 @@ module.exports = function (limits, now) {
...
   }
 
+  EmailRecord.prototype.isOverSmsLimit = function () {
+    this.trimSmsRequests(now())
+    return this.sms.length > limits.maxSms
+  }
+
+  EmailRecord.prototype.trimSmsRequests = function (now) {
+    if (this.sms.length === 0) { return }
+    // vc is naturally ordered from oldest to newest
```
Comment (rfk) [inline lib/email_record.js]: s/vc/sms/ in this comment

**Comment by vbudhram** [comment]
Thanks @rfk!
